-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "1920x1080@60.16", position = "3551x0", scale = 1.20 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.00", position = "1920x-40", scale = 1.20 })
